# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac866d52c655eacfcae2479e97e4372b100495db987ec9cdd44896ccbea546da3e0593ca56a0e7ca6493d5b3eb8e7ede555f3ef93daa262d2f0d022b6787b001

test:
  secret_key_base: 59052baec5ed833bd2cf3ed29b7487c460a8e39c95bf911f452546a7dd364925a317c63f02cb92353df3563f079bcc741c85ef852bcec2d3a9d2f740fcbc294e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
